plugins {
    id 'com.android.application'
}

android {
    namespace 'com.seiryu.sunoexport'
    compileSdk 35

    defaultConfig {
        applicationId 'com.seiryu.sunoexport.s10e'
        minSdk 26
        targetSdk 31
        versionCode 2
        versionName '0.1.1-s10e'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            v1SigningEnabled true
            v2SigningEnabled true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
